'use client';
import { FormEvent, useEffect, useState } from 'react';

const services = [{ id:'classic',name:'Classic set',price:'R650' },{ id:'hybrid',name:'Hybrid set',price:'R780' },{ id:'volume',name:'Volume set',price:'R900' }];
const times = ['09:00','10:30','12:00','14:00','15:30','17:00'];

export function BookingForm() {
  const [service,setService]=useState('classic'),[date,setDate]=useState(''),[time,setTime]=useState('');
  const [unavailable,setUnavailable]=useState<string[]>([]),[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'),[message,setMessage]=useState('');
  useEffect(()=>{if(!date){setUnavailable([]);return}fetch(`/api/bookings?date=${encodeURIComponent(date)}`).then(r=>r.ok?r.json():{unavailable:[]}).then(data=>{setUnavailable(data.unavailable||[]);if(data.unavailable?.includes(time))setTime('')}).catch(()=>setUnavailable([]))},[date,time]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=context.registerTool({name:'create_lash_booking',title:'Book a lash appointment',description:'Create a Lash by Design appointment request for a selected service, date and available time.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['classic','hybrid','volume']},date:{type:'string',format:'date'},time:{type:'string',enum:times},name:{type:'string',minLength:1},email:{type:'string',format:'email'},phone:{type:'string',minLength:1},notes:{type:'string'}},required:['service','date','time','name','email','phone'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const response=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Booking could not be created');setStatus('success');setMessage(result.reference);return{reference:result.reference,status:'requested'}}},{signal:lifecycle.signal});
    Promise.resolve(register).catch(()=>{});return()=>lifecycle.abort();
  },[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('sending');setMessage('');const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch('/api/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,service,date,time})});const result=await response.json().catch(()=>({}));if(!response.ok){setStatus('error');setMessage(result.error||'We could not save your booking. Please try again.');return}setStatus('success');setMessage(result.reference)}
  if(status==='success')return <div className="booking-form success-card" role="status"><span>✓</span><p className="eyebrow">Appointment requested</p><h3>You’re on the books.</h3><p>Your reference is <b>{message}</b>. Lash by Design will confirm your appointment using the contact details provided.</p><button className="button primary" onClick={()=>{setStatus('idle');setDate('');setTime('')}}>Book another</button></div>;
  return <form className="booking-form" onSubmit={submit}><fieldset><legend>1. Choose your set</legend><div className="choice-grid">{services.map(item=><button type="button" key={item.id} className={service===item.id?'choice selected':'choice'} onClick={()=>setService(item.id)} aria-pressed={service===item.id}><span>{item.name}</span><b>{item.price}</b></button>)}</div></fieldset><fieldset><legend>2. Pick a time</legend><label className="field"><span>Date</span><input name="date" type="date" required value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>{setDate(e.target.value);setTime('')}}/></label><div className="time-grid">{times.map(item=><button type="button" key={item} disabled={!date||unavailable.includes(item)} className={time===item?'time selected':'time'} onClick={()=>setTime(item)} aria-pressed={time===item}>{item}{unavailable.includes(item)&&<small>Booked</small>}</button>)}</div></fieldset><fieldset><legend>3. Your details</legend><div className="form-grid"><label className="field"><span>Name</span><input name="name" autoComplete="name" required/></label><label className="field"><span>Phone</span><input name="phone" autoComplete="tel" required/></label><label className="field full"><span>Email</span><input name="email" type="email" autoComplete="email" required/></label><label className="field full"><span>Anything we should know? <small>Optional</small></span><textarea name="notes" rows={3}/></label></div></fieldset>{status==='error'&&<p className="form-error" role="alert">{message}</p>}<button className="button primary submit" disabled={!date||!time||status==='sending'}>{status==='sending'?'Saving your appointment…':'Request appointment'}</button></form>;
}
